[package]
name = "gpg-tui"
version = "0.9.4"
description = "Manage your GnuPG keys with ease!"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/gpg-tui"
homepage = "https://github.com/orhun/gpg-tui"
repository = "https://github.com/orhun/gpg-tui"
keywords = ["gnupg", "gpg", "tui", "key", "management"]
categories = ["command-line-utilities"]
include = ["src/**/*", "assets/*", "Cargo.*", "LICENSE", "README.md", "CHANGELOG.md"]
edition = "2021"
default-run = "gpg-tui"
rust-version = "1.64.0"

[[bin]]
name = "gpg-tui-completions"
path = "src/bin/completions.rs"
test = false

[features]
tui-tests = []
gpg-tests = []

[dependencies]
gpgme = "0.11.0"
tui = { package = "ratatui", version = "0.20.1" }
anyhow = "1.0.69"
chrono = "0.4.23"
unicode-width = "0.1.10"
copypasta-ext = "0.4.1"
colorsys = "0.6.7"
rust-embed = "6.4.2"
shellexpand = "3.0.0"
hex-literal = "0.3.4"
toml = "0.7.2"
dirs-next = "2.0.0"
clap_complete = "3.2.5"
tinytemplate = "1.2.1"

[dependencies.crossterm]
version = "0.26.0"
features = ["serde"]

[dependencies.clap]
version = "3.2.23"
features = ["derive", "env", "wrap_help"]

[dependencies.image]
version = "0.24.5"
default-features = false
features = ["jpeg"]

[dependencies.serde]
version = "1.0.152"
features = ["derive"]

[dev-dependencies]
pretty_assertions = "1.3.0"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "abort"
lto = true
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
